theme:
  default: style-light
# è¯­è¨€
language: zh-Hans
# ç½‘ç«™å›¾æ ‡Favicon
favicon:
  logo: /img/favicon.svg
  icon16: favicon-16x16.png
  icon32: favicon-32x32.png
  visibilitychange: true

#ç”¨æˆ·ä¿¡æ¯
user:
  name: å¼ é±¼é”…å·´
  first_name: é”…å·´
  last_name: å¼ é±¼
  email: 1120306825@qq.com
  avatar: /img/avatar.jpg
  domain: https://1999zaz.github.io
  describe: äº‘å·äº‘èˆ’,
  birthDay: 07/09/1999
  ruleText: æš‚ä¸æ¥å—ä¸ªäººåšå®¢ä»¥å¤–çš„å‹é“¾ç”³è¯·ï¼Œç¡®ä¿æ‚¨çš„ç½‘ç«™å†…å®¹ç§¯æå‘ä¸Š,éƒ¨ç½²HTTPSã€‚

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  double_arrows: fas fa-angle-double-down
  copy: fas fa-copy

# logo

top_bars:
  - title: Home
    url: /
  - title: ğŸŒå…‰è£è¿›åŒ–
    url: /archives/
  - title: ğŸƒLink
    url: /links/
  - title: ğŸ¤¸About
    url: /about/
  - title: ğŸ“¸ç›¸å†Œ
    url: /gallery/

sidebar:
  typedTextPrefix: 2023
  typedText: ["ä¸‡äº‹èƒœæ„"]
  info: # ä¸ªäººä¿¡æ¯
    - key: åœ°å€
      val: å®‰å¾½
    - key: å¹´é¾„
      val: 18 forever
    - key: Hobby
      val: ç¾é£Ÿä¸å®…ä¸play
    - key: æ‰å
      val: æ‰é«˜å…«æ–—,å…±æœ‰å…«ç™¾æ–—!!

  social:
    - icon: fab fa-github
      url: https://github.com/1999zaz
      name: Github
    - icon: fab fa-alipay
      name: Alipay
    - icon: fab fa-weixin
      name: Weixin
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: æˆ‘è§å±±æ²³æ¶Œ ä¼¼æ˜¯æ•…äººæ¥
    bannerText: Welcome to my World!
  archive:
    bgurl: https://images.pexels.com/photos/14530150/pexels-photo-14530150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
    bannerTitle: è¿™è·¯é¥é©¬æ€¥çš„äººé—´<br>â³â³â³â³â³â³
    bannerText: The article archive
  links:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: è¿™æ˜¯æˆ‘çš„ç›Šè¾¾ <br>ä¸!æ˜¯ä½ çš„ç›Šè¾¾
    bannerText: Between u and m
  about:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: ä½ çš„...<br>å¤´å‘ä¹±äº†
    bannerText: About me

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 2022/04/10 17:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: false
  max_depth: 3
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination:
  enable: true
  type: small

highlight:
  title: mac
  height_limit: 200

cover:
  default:
    - /img/block.jpg
  type: random

categorie_card:
  enable: true
  len: 2
  list: ["ç”Ÿæ´»è®°å½•", "å­¦ä¹ ä¹‹è·¯"]
