theme:
  default: style-light
# è¯­è¨€
language: zh-Hans
# ç½‘ç«™å›¾æ ‡Favicon
favicon:
  logo: /img/favicon.svg
  icon16: favicon-16x16.png
  icon32: favicon-32x32.png
  visibilitychange: true

#ç”¨æˆ·ä¿¡æ¯
user:
  name: å¼ é±¼é”…å·´
  first_name: é”…å·´
  last_name: å¼ é±¼
  email: 1120306825@qq.com
  avatar: /img/avatar.jpg
  describe: äº‘å·äº‘èˆ’,
  birthDay: 07/09/1999

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  double_arrows: fas fa-angle-double-down
  copy: fas fa-copy

# logo

top_bars:
  - title: é¦–é¡µ
    url: /
  - title: ğŸŒå…‰è£è¿›åŒ–
    url: /archives/
  - title: ğŸ¤¸About
    url: /about/
  - title: ğŸƒDIY
    url: /customize_page/
  - title: ğŸ“¸ç›¸å†Œ
    url: /gallery/

sidebar:
  typedTextPrefix: 2023
  typedText: ["ä¸‡äº‹èƒœæ„"]
  info: # ä¸ªäººä¿¡æ¯
    - key: åœ°å€
      val: å®‰å¾½
    - key: å¹´é¾„
      val: 18 forever
    - key: Hobby
      val: ç¾é£Ÿä¸å®…ä¸play
    - key: æ‰å
      val: æ‰é«˜å…«æ–—,å…±æœ‰å…«ç™¾æ–—!!

  social:
    - icon: fab fa-github
      url: https://github.com/MaLuns/Hexo-theme-async
      name: Github
    - icon: fab fa-alipay
      name: Alipay
    - icon: fab fa-weixin
      name: Weixin
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: æˆ‘è§å±±æ²³æ¶Œ<br>ä¼¼æ˜¯æ•…äººæ¥
    bannerText: Welcome to my World!
  archive:
    bgurl: https://images.pexels.com/photos/14530150/pexels-photo-14530150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
    bannerTitle: è¿™è·¯é¥é©¬æ€¥çš„äººé—´<br>â³â³â³â³â³â³
    bannerText: The article archive
  links:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: è¿™æ˜¯æˆ‘çš„ç›Šè¾¾<br>ä¸!æ˜¯ä½ çš„ç›Šè¾¾
    bannerText: A link to a friend's website
  about:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: ä½ çš„...<br>å¤´å‘ä¹±äº†
    bannerText: About me

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 2022/04/10 17:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: false
  max_depth: 3
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination:
  enable: true
  type: small

highlight:
  title: mac
  height_limit: 200

cover:
  default:
    - /img/block.jpg
    - https://th.wallhaven.cc/orig/wq/wqvkl7.jpg
    - https://th.wallhaven.cc/orig/rd/rdq3v1.jpg
    - https://th.wallhaven.cc/orig/rd/rd183j.jpg
    - https://th.wallhaven.cc/orig/q2/q287wd.jpg
    - https://th.wallhaven.cc/orig/g7/g79ov3.jpg
    - https://th.wallhaven.cc/orig/q2/q2mkzr.jpg
    - https://th.wallhaven.cc/orig/v9/v9j3yp.jpg
    - https://th.wallhaven.cc/orig/y8/y8yvzx.jpg
    - https://th.wallhaven.cc/orig/1k/1kdw2w.jpg
    - https://th.wallhaven.cc/orig/57/57jqk1.jpg
    - https://th.wallhaven.cc/orig/57/5762p1.jpg
    - https://th.wallhaven.cc/orig/j3/j3zo1y.jpg
    - https://th.wallhaven.cc/orig/m9/m9gkky.jpg
    - https://th.wallhaven.cc/orig/e7/e7kv9k.jpg
    - https://th.wallhaven.cc/orig/ym/ym9ldk.jpg
    - https://th.wallhaven.cc/orig/pk/pk5259.jpg
    - https://th.wallhaven.cc/orig/8o/8opxpk.jpg
    - https://th.wallhaven.cc/orig/k7/k7yog7.jpg
    - https://th.wallhaven.cc/orig/v9/v93zv3.jpg
    - https://th.wallhaven.cc/orig/wq/wqj65q.jpg
    - https://th.wallhaven.cc/orig/p9/p9kg1m.jpg
    - https://th.wallhaven.cc/orig/8o/8o9vw1.jpg
    - https://th.wallhaven.cc/orig/x8/x8yy3o.jpg
  type: random
